# Import Library

In [4]:
import pandas as pd
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

# Data Loading

In [5]:
data=pd.read_csv('inference.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7255 entries, 0 to 7254
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            7255 non-null   object
 1   no_of_adults                          7255 non-null   int64
 2   no_of_children                        7255 non-null   int64
 3   no_of_weekend_nights                  7255 non-null   int64
 4   no_of_week_nights                     7255 non-null   int64
 5   type_of_meal_plan                     7255 non-null   object
 6   required_car_parking_space            7255 non-null   int64
 7   room_type_reserved                    7255 non-null   object
 8   lead_time                             7255 non-null   int64
 9   arrival_year                          7255 non-null   int64
 10  arrival_month                         7255 non-null   int64
 11  arrival_date                          7255 non-null   int64
 12  market_segment_type                   7255 non-null   object
 13  repeated_guest                        7255 non-null   int64
 14  no_of_previous_cancellations          7255 non-null   int64
 15  no_of_previous_bookings_not_canceled  7255 non-null   int64
 16  avg_price_per_room                    7255 non-null   float64
 17  no_of_special_requests                7255 non-null   int64
dtypes: float64(1), int64(13), object(4)
memory usage: 1020.4+ KB

In [7]:
model = keras.models.load_model('func_model.hdf5')
with open('feature.json','r') as f:
    import json
    feature = json.load(f)
import joblib
trans = joblib.load('transformer.pkl')

trained = data[feature]
trained = trans.transform(trained)
pred = np.where(model.predict(trained)>0.5,'Cancelled','Not Canceled')

227/227 [==============================] - 0s 1ms/step

In [8]:
data['pred'] = pred
data

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,pred
0,ID34591,2,0,2,1,Meal Plan 2,0,Room_Type 1,138,2017,8,22,Offline,0,0,0,94.50,0,Cancelled
1,ID25655,1,0,0,4,Not Selected,0,Room_Type 1,2,2018,10,19,Online,0,0,0,134.00,0,Not Canceled
2,ID04852,1,0,1,2,Meal Plan 1,1,Room_Type 1,0,2017,11,9,Online,0,0,0,100.00,1,Not Canceled
3,ID10085,2,0,0,2,Meal Plan 1,0,Room_Type 1,22,2017,11,26,Online,0,0,0,97.00,0,Not Canceled
4,ID17688,1,0,0,3,Meal Plan 1,0,Room_Type 1,14,2017,9,15,Online,0,0,0,114.00,1,Not Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7250,ID34939,3,0,2,2,Meal Plan 1,0,Room_Type 4,50,2018,7,10,Online,0,0,0,142.20,0,Cancelled
7251,ID27166,2,2,2,5,Meal Plan 1,0,Room_Type 5,190,2018,8,10,Online,0,0,0,117.51,2,Cancelled
7252,ID23297,1,0,0,2,Meal Plan 1,0,Room_Type 1,2,2018,12,14,Corporate,1,0,22,65.00,1,Not Canceled
7253,ID12250,2,0,2,5,Meal Plan 1,0,Room_Type 5,57,2018,4,22,Online,0,0,0,105.25,0,Cancelled
7254,ID20789,2,0,0,3,Meal Plan 1,0,Room_Type 4,21,2017,11,3,Offline,0,0,0,46.67,0,Not Canceled